[package]
name = "mk"
description = "Text preprocessor for content segmentation"
version = "0.1.4"
edition = "2021"

[dependencies]
clap = { version = "4.5.8", features = ["derive"] }
glob = "0.3.1"
once_cell = "1.19.0"
rand = "0.8.5"
toml = "0.8.14"
