[package]
name = "mk"
description = "Text preprocessor for content segmentation"
version = "0.1.7"
edition = "2021"

[dependencies]
clap = { version = "4.5.20", features = ["derive"] }
clap_complete = { version = "4.5.33", features = ["unstable-dynamic"] }
glob = "0.3.1"
once_cell = "1.20.2"
rand = "0.8.5"
toml = "0.8.19"
